[workspace]
members = [
	"contracts/*",
	"packages/*",
	]

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/Arena-DAO/arena-smart-contracts"
version = "0.1.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-std = { version = "1.2.4", features = ["ibc3"] }
cosmwasm-storage = { version = "1.2.4" }
cosmwasm-schema = { version = "1.2.4" }
cw-utils = "1.0.1"
thiserror = { version = "1.0.40" }
cw-storage-plus = "1.0.1"
cw-multi-test = { rev = "9af32fd42efcf28e9a79987f2c2036f879cd5331", git = "https://github.com/CosmWasm/cw-multi-test" }
cw2 = "1.0.1"
cw20 = "1.0.1"
cw721 = "0.17.0"
cw20-base = "1.0.1"
cw721-base = "0.17"
cw-controllers = "1.0.1"
anyhow = { version = "1.0.70"}
cw4-group = "1.0.1"
rand = "0.8"
cw4 = "1.0.1"
serde = "1.0"
getrandom = { version = "0.2.9", features = ["js"] }

#arena_dao dependencies
cw-competition = { path = "./packages/cw-competition" }
cw-balance = { path = "./packages/cw-balance" }
arena-testing = { path = "./packages/arena-testing" }

arena-core = { path = "./contracts/arena-core" }
arena-escrow = { path = "./contracts/arena-escrow" }
arena-wager-module = { path = "./contracts/arena-wager-module" }

#dao dependencies
dao-core = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"]}
dao-interface = { git = "https://github.com/DA0-DA0/dao-contracts" }
dao-proposal-multiple = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"]}
dao-voting = { git = "https://github.com/DA0-DA0/dao-contracts" }
dao-voting-cw4 = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"]}
dao-proposal-sudo = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"]}
dao-pre-propose-base = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"] }
dao-testing = { git = "https://github.com/DA0-DA0/dao-contracts" }