[package]
name = "cw-competition-base"
authors = ["ismellike <glopez11193@gmail.com>"]
description = "A package designed for creating modular competitions in smart contracts."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
cw-utils = { workspace= true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }

cw2 = { workspace = true }
cw4 = { workspace = true }
cw-balance = { workspace = true }
cw-ownable = { workspace = true }
cw-competition = { workspace = true }
cw-paginate = { workspace = true }
arena-core-interface = { workspace = true }

dao-interface = { workspace = true }
dao-pre-propose-base = { workspace = true }
dao-voting = { workspace = true }