[package]
name = "arena-testing"
authors = ["ismellike <glopez11193@gmail.com>"]
description = "This package provides a set of helper functions to create tests for multiple CosmWasm contracts."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
arena-core = { workspace = true }
arena-escrow = { workspace = true }
arena-wager-module = { workspace = true }
arena-league-module = { workspace = true }
dao-proposal-multiple = { workspace = true }
cw-multi-test = { workspace = true }
cw20-base = { workspace = true }
cw721-base = { workspace = true }
dao-proposal-single = { workspace = true }
dao-dao-core = { workspace = true }
cw4-group = { workspace = true }
dao-voting-cw4 = { workspace = true }